version: "3"
services:
  db:
    container_name: 'db'
    image: 'postgres'
    ports:
      - '5433:5432'
    environment:
      POSTGRES_PASSWORD: '1234'
      POSTGRES_DB: 'hospitalDB'

    volumes:
      - hp-data:/var/lib/postgresql/data
    networks:
      - 'mynet'

  app:
    container_name: 'hpapp'
    image: 'hp'
    build: .
    restart: 'on-failure'
    ports:
      - '8080:8080'
    environment:
      DB_HOST: 'db'
      DB_USER: 'postgres'
      DB_PASSWORD: '1234'
      DB_PORT: '5432'
      DB_NAME: 'hospitalDB'
    networks:
      - 'mynet'
    depends_on:
      - 'db'
networks:
  mynet:
    external: true
volumes:
  hp-data: