name: Build, Push & Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build with Maven (skip tests)
        run: mvn clean package -DskipTests

      - name: Build Docker image
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/hp:latest .

      - name: Login to DockerHub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Push image to DockerHub
        run: docker push ${{ secrets.DOCKER_USERNAME }}/hp:latest

      - name: Decode EC2 SSH key
        run: |
          echo "${{ secrets.EC2_KEY }}" | base64 -d > ec2key.pem
          chmod 600 ec2key.pem

      - name: SSH and deploy on EC2
        run: |
          ssh -i ec2key.pem -o StrictHostKeyChecking=no ${{ secrets.EC2_USERNAME }}@${{ secrets.EC2_HOST }} << EOF
            docker pull ${{ secrets.DOCKER_USERNAME }}/hp:latest
            docker-compose down
            docker-compose up -d
        EOF
